package `in`.singhangad.adkassistant.data.agent

import com.google.adk.kt.agents.Instruction
import com.google.adk.kt.agents.LlmAgent
import com.google.adk.kt.models.Gemini
import `in`.singhangad.adkassistant.BuildConfig
import javax.inject.Inject

/**
 * Builds the assistant [LlmAgent] — a cloud Gemini model plus the local
 * [DeviceTools]. Lives in the data layer because it knows about ADK + Gemini.
 */
class AssistantAgentFactory @Inject constructor() {

    fun create(modelName: String): LlmAgent = LlmAgent(
        name = "device_assistant",
        description = "A helpful assistant that can read the device clock and hardware info.",
        // The model id is chosen by the user (model dropdown). It can 503 ("high
        // demand") under load — the repository rides that out with retry + backoff.
        model = Gemini(
            name = modelName,
            apiKey = BuildConfig.GEMINI_API_KEY,
        ),
        instruction = Instruction(
            "You are a concise on-device assistant. " +
                "When the user asks about the time, use the 'getCurrentTime' tool. " +
                "When they ask about the phone or device, use the 'getDeviceInfo' tool. " +
                "Never invent values you can get from a tool."
        ),
        // generatedTools() is generated by KSP from the @Tool annotations above.
        tools = DeviceTools().generatedTools(),
    )
}
